name: 'Grid.ai BYOC Create'
on:
  push:
    paths:
      - action.yml
      - .github/workflows/unittest.yml
jobs:
  unittests:
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        os: [ubuntu-latest] #, macos-latest,windows-latest]
        python-version: [3.8] #,3.9]       
        python-venv: [""] #,"venv"]
        byoc-cost-savings: ["--cost-savings"] #, ""]
        byoc-region: ["--region us-east-1"]       
        byoc-instance-types: ["--instance-types t2.medium,g4dn.xlarge"]       
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60 # takes about 20 min to create the cluster
    steps:
      - uses: actions/checkout@v2     
      - uses: gridai-actions/gridai-login@main
        with:
          python-version: ${{ matrix.python-version }}
          python-venv: ${{ matrix.python-venv }}
          gridai-username: ${{ secrets.GRIDAI_USERNAME }} 
          gridai-key: ${{ secrets.GRIDAI_KEY }}
      - id: gridai-obj-create
        uses: gridai-actions/gridai-byoc@main
        with:
          grid-args: ${{ matrix.byoc-cost-savings }} ${{ matrix.byoc-region }} ${{ matrix.byoc-instance-types }}
          success-status: "[running|failed]"
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}           
# TODO: perform a run
      - uses: actions/checkout@v2     
        with:
          repository: robert-s-lee/hello
      - uses: gridai-actions/gridai-run@main
        with:
          cluster-name: ${{ steps.gridai-obj-create.outputs.obj-id }}
          script-dir: ${GITHUB_WORKSPACE}
          script-name: hello.py
# TODO: perform a session
# TODO: perform a datastore
      - run:
          grid delete cluster ${{ steps.gridai-obj-create.outputs.obj-id }} 